[build]
  publish = "."
  functions = "api"  # Points to your api folder

[functions]
  node_bundler = "esbuild"

  [functions."*"]
    timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
